### ISSUE TITLE
zone is currently a stub

### ISSUE THREAD

**Issue by hannesm** [mirage/ns.mirage.io#1]
@avsm please fill with a current zone dump for mirage.io (and openmirage.org as well?)

**Comment by avsm** [comment]
Dumping the current Gandi contents here:


```
@ 600 IN A 46.43.42.136
canopy 10800 IN A 62.176.169.169
ci 3600 IN A 147.75.101.83
git 10800 IN A 162.242.173.151
infra-1 10800 IN A 147.75.106.53
marrakech2017 10800 IN A 198.167.222.204
solo5 10800 IN A 147.75.195.128
xen 10800 IN A 147.75.195.129
xen-1 10800 IN A 147.75.101.93
xen-2 10800 IN A 147.75.101.73
docs 10800 IN CNAME miragedoc.miragedoc.90257e2c.svc.dockerapp.io.
icfp2016 10800 IN CNAME icfp2016.icfp2016.aa2d34ed.svc.dockerapp.io.
@ 10800 IN MX 50 fb.mail.gandi.net.
@ 10800 IN MX 10 spool.mail.gandi.net.
```

**Comment by hannesm** [comment]
//cc @mato

**Comment by hannesm** [comment]
Thanks @avsm 

I just setup two servers (in different /24) acting as nameserver for mirage.io, serving both the very same zone (these are actually the very same unikernel images (ip configuration and syslog is provided via boot parameters) :)

If you feel confident (e.g. by checking that the zone above and the zone in this repository is equal, and also served by the nameservers), please modify at gandi and provide them with our own nameservers (ns0.mirage.io -- 198.167.222.212 and ns1.mirage.io -- 194.150.168.147):

```
# dig soa mirage.io @194.150.168.147

; <<>> DiG 9.11.1-P3 <<>> soa mirage.io @194.150.168.147
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 2562
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 2, ADDITIONAL: 3
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags: do; udp: 1500
;; QUESTION SECTION:
;mirage.io.                     IN      SOA

;; ANSWER SECTION:
mirage.io.              604800  IN      SOA     ns0.mirage.io. we.mirage.io. 2017073001 16384 2048 1048576 2560

;; AUTHORITY SECTION:
mirage.io.              604800  IN      NS      ns0.mirage.io.
mirage.io.              604800  IN      NS      ns1.mirage.io.

;; ADDITIONAL SECTION:
ns1.mirage.io.          604800  IN      A       194.150.168.147
ns0.mirage.io.          604800  IN      A       198.167.222.212
```

**Comment by hannesm** [comment]
@avsm what delays a switch to our own DNS infrastructure?  if I can help further with switching from gandhi to our own NS, please let me know.

**Comment by avsm** [comment]
thanks! i'd like to also host one of the unikernels on infrastructure being setup at the Computer Lab.

How do these update? Do they poll this github repo for changes and reboot?

**Comment by hannesm** [comment]
no automated update yet

**Comment by hannesm** [comment]
since @avsm first wants to sort out his mirage infrastructure (and stay in full control thereof), I'm closing this.  the above mentioned nameservers are not running anymore.
